#### Weight & Biases settings

wandb:
  name: "2024-05-13 - First run"
  resume: True
  job_type: "Train-Test"
  group: "Exercise 1"
  project: "University - DLA - Lab 2"
  tags: 
  - "NanoGPT"
  - "LLM"
  - "NLP"
  - "Base"

  notes: "First attempt at training a basic NanoGPT."


#### Experiment settings

config:
  # Machine
  seed: 1
  device: "cuda:0"

  # Paths and dirs
  data: "divina_commedia.txt"
  results_dir: "results"
  log_file: "log.txt"

  model_type: "NanoGPT"
  model:
    block_size: 256 # what is the maximum context length for predictions?
    n_embd: 384
    n_head: 6
    n_layer: 6
    dropout: 0.2
  
  # criterion: "CrossEntropyLoss"

  # dataset:
  #   dataset_name: "CIFAR10"
  #   val_size: 0.2
  #   val_shuffle: True
  #   normalize: True
  #   augment: True
  #   use_sampler: True
  
  dataloader:
  #   num_workers: 4
    batch_size: 64  # how many independent sequences will we process in parallel?
  #   pin_memory: True
  #   persistent_workers: True

  optimizer_name: "AdamW"  # Lion, Adam, SGD, Adamax, Adadelta, RMSProp ecc. (https://pytorch.org/docs/stable/optim.html)
  optimizer:
    lr: 0.0003
    weight_decay: 0.01
    amsgrad: True
  
  scheduler_name: "OneCycleLR"  # MultiStepLR
  scheduler: 
    max_lr: 0.0001
  
  pretrain: False
  pretest: False
  train: True
  test: True

  training:
    n_epochs: 5000
    eval_interval: 500
    checkpoint_every: 10
    patience: 20

  clip_grads: False

  # Goals
  problem: None
  xai: False
  explain_gradients: False
  explain_cam: False